### ISSUE TITLE
[BUG/Help] <title> AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by superggfun** [THUDM/ChatGLM-6B#1089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|██████████| 8/8 [00:08<00:00,  1.02s/it]
Traceback (most recent call last):
  File "C:\Users\21922\Desktop\chat\ChatGLM-6B\cli_demo.py", line 7, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\21922\Desktop\chat\ChatGLM-6B\venv\Lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\21922\Desktop\chat\ChatGLM-6B\venv\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\21922\Desktop\chat\ChatGLM-6B\venv\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\21922\Desktop\chat\ChatGLM-6B\venv\Lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\Users\21922\Desktop\chat\ChatGLM-6B\venv\Lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
                                 ^^^^^^^^^^^^^^
  File "C:\Users\21922\Desktop\chat\ChatGLM-6B\venv\Lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

### Steps To Reproduce

I have installed CUDA, NVCC, CUDNN, pytorch, and used
```
import torch
print(torch.cuda.is_available())
print(torch.backends.cudnn.is_available())
print(torch.cuda_version)
print(torch.backends.cudnn.version())
```
Passed the test, But there are still errors during operation.

### Environment

```markdown
- OS: Windows
- Python: 3.11
- Transformers: 4.27.1
- PyTorch: 11.7
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by worm128** [comment]
我也是这样，我的是AMD显卡，我安装的是torch的CPU版本，仍然不行

**Comment by superggfun** [comment]
> 我也是这样，我的是AMD显卡6700XT，我安装的是torch的CPU版本，仍然不行

我后来解决了。你是AMD显卡当然不行，它不支持CUDA啊。必须要英伟达显卡

**Comment by worm128** [comment]
> > 我也是这样，我的是AMD显卡6700XT，我安装的是torch的CPU版本，仍然不行
> 
> 我后来解决了。你是AMD显卡当然不行，它不支持CUDA啊。必须要英伟达显卡

AMD显卡只能跑CPU模式吗？我看了一下ROCm是否只支持linux系统，不支持window

**Comment by superggfun** [comment]
你是AMD，只能用CPU跑了，不能用显卡跑。

Winlone囧v ***@***.***> 于 2023年9月5日周二 下午1:47写道：
